### ISSUE TITLE
Invalid default value for prop testStyle

### ISSUE THREAD

**Issue by DSchmidlin** [biigpongsatorn/vue-element-loading#14]
Invalid default value for prop "textStyle": Props with type Object/Array must use a factory function to return the default value.

**Comment by biigpongsatorn** [comment]
Thanks. Solved in #15

**Comment by ciryon** [comment]
Hi @biigpongsatorn, I still get ```vue.runtime.esm.js?2b0e:601 [Vue warn]: Invalid default value for prop "textStyle": Props with type Object/Array must use a factory function to return the default value.``` when using version 1.1.0.

**Comment by biigpongsatorn** [comment]
@ciryon  Please try to uninstall this package and install it again. And please check version in `package-lock`.

**Comment by kadinho** [comment]
@biigpongsatorn I get the same issue too @1.1.0 and a reinstalled the package as you suggested, also removed the package completely and did a fresh install again, no success. Checked the code and still the "old" version:
`textStyle:{type:Object,default:{}}`

Can you please check ?

tx

> Hi @biigpongsatorn, I still get `vue.runtime.esm.js?2b0e:601 [Vue warn]: Invalid default value for prop "textStyle": Props with type Object/Array must use a factory function to return the default value.` when using version 1.1.0.

**Comment by biigpongsatorn** [comment]
@kadinho Sorry about that, Let's me check.

**Comment by biigpongsatorn** [comment]
Please try again in version 1.1.1

**Comment by ciryon** [comment]
@biigpongsatorn thanks works now!

**Comment by ClaudioVarandas** [comment]
tx!
