### ISSUE TITLE
Not working in IE 11 - getting Script Syntax error

### ISSUE THREAD

**Issue by samteb** [biigpongsatorn/vue-element-loading#19]
I am using weback to bundle my files and I get a console error `SCRIPT1002: Syntax error`.
I don't understand where it comes from ... Does someone have an idea ?

**Comment by samteb** [comment]
Hey nothing here ?

**Comment by biigpongsatorn** [comment]
I can't debug it because I have no IE to test this issue. sorry

**Comment by wizzout** [comment]
Seems like your bili driven bundler is not configured enough. It leaves one arrow function in compiled lib file, so IE cant handle it. https://monosnap.com/file/zNQLVjJ0KH8kPuL5t5yZASEX7cJFq8

**Comment by samteb** [comment]
@wizzout thanks for answering! @biigpongsatorn can you investigate ?

**Comment by biigpongsatorn** [comment]
@samteb OK, I will try

**Comment by biigpongsatorn** [comment]
I think the problem is maybe not from `arrow function` but I can't debug this issue because I have no IE for testing. @samteb  Can you make the PR to solve this issue?

**Comment by joachimVT** [comment]
I am having the same issue `return(t,e)=>`on  in Internet Explorer 11

**Comment by Coverttrickster** [comment]
I'm having the same issue. I tried to transpile it in vue.config.js but doesn't seem to affect it at all. Any ideas?

**Comment by sktzofrenic** [comment]
Guys, this is fixed here: sktzofrenic:dan/ie11-fix 

I'm sure there is a bili setting that can be modified, but this works also.

**Comment by biigpongsatorn** [comment]
Please try version `1.1.2`

**Comment by biigpongsatorn** [comment]
I just fix this bug in `vue-element-loading.min.js` manually and publish to version `1.1.5`.

Please try again.

**Comment by samteb** [comment]
Thanks for this fix
