### ISSUE TITLE
How do you stop the spinner?

### ISSUE THREAD

**Issue by princedacy** [biigpongsatorn/vue-element-loading#2]
The spinner keeps loading even after the component has loaded all the data.
How do you stop it or give it a timer like a certain number of seconds?

**Comment by biigpongsatorn** [comment]
@princedacy  You can stop spinner by set `active` attribute = `false`.

example
```html
<template>
   <vue-element-loading :active="isActive"/>
</template>

<script>
export default {
   data () {
      return {
         isActive: false
      }
   },
   async created () {
      this.isActive = true
      await this.getSomeData()
      this.isActive = false
   }
}
</script>
```

**Comment by biigpongsatorn** [comment]
@princedacy  Can I close this issue ?

**Comment by princedacy** [comment]
that async created function returns an error that it is not a function

**Comment by biigpongsatorn** [comment]
@princedacy  `await this.getSomeData()` is your load data function. This is just example.
