### ISSUE TITLE
Size is not taking effect

### ISSUE THREAD

**Issue by enghelewa** [biigpongsatorn/vue-element-loading#21]
Size is always `40px` whatever value you pass its always the same
```
<button @click="apply(props.row)" class="btn green-haze">
      <span v-if="!applying"><i class="fas fa-check"></i> Apply</span>
      <vue-element-loading :active="applying" size="25" spinner="ring" color="#ffffff"/>
</button>
```

**Comment by biigpongsatorn** [comment]
I try to change size in my example page, it's work correctly. Please check your custom style

https://vue-element-loading.netlify.com/

![image](https://user-images.githubusercontent.com/10693658/60574907-ad590300-9da4-11e9-89c3-f2cebfac5717.png)

**Comment by enghelewa** [comment]
Sorry for that. The issue was because I am using an outdated version.
I think that docs need to be updated to address faetures with the related version numbers required. :)

**Comment by biigpongsatorn** [comment]
PR welcome :)
