### ISSUE TITLE
Set default config

### ISSUE THREAD

**Issue by movepixels** [biigpongsatorn/vue-element-loading#22]
Is there a way when using as a component to set default config so you dont have to put it in every place the loader is used?

```
import Vue from 'vue'
import VueElementLoading from 'vue-element-loading'

const options = {
     spinner:"spinner",
     color:"#E91E63"
}

Vue.component('VueElementLoading', VueElementLoading)
```

**Comment by biigpongsatorn** [comment]
not sure, please try
```
Vue.component('VueElementLoading', {
  extends: VueElementLoading,
  props: {
     spinner:"spinner",
     color:"#E91E63"
  }
});
```

**Comment by movepixels** [comment]
Results in error stating:

```
Right-hand side of 'instanceof' is not an object
```

**Comment by movepixels** [comment]
SOLVED

Has to be in the correct format of props:

```
Vue.component('VueElementLoading', {
  extends: VueElementLoading,
  props: {
    size: {
      type: String,
      default: '128'
    },
    spinner: {
      type: String,
      default: 'spinner'
    },
    color: {
      type: String,
      default: '#9ea72e'
    },
    backgroundColor: {
      type: String,
      default: 'rgba(255, 255, 255, .5)'
    }
  }
})
```

If anyone come across this or if you want to add it to the docs. Beats having to set the same props everytime :)

Dave

**Comment by biigpongsatorn** [comment]
@movepixels Cool! Thank you for your suggestion. PR welcome if you want to contribute this path :)

**Comment by movepixels** [comment]
Hello,

 

Sure I will help out.

 

I need to take the day to look at what changed from 1.0.5 to now 1.1.1. I am using this in Nuxt app and in 1.0.5 I get no errors. Anything over 1.0.5 I get the 
“The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.” Error in console so something changed to break.

 

Off hand you know what major changes were made? I will go back and look all the same.
