### ISSUE TITLE
Arrow function not transpiled in vue-element-loading.min.js

### ISSUE THREAD

**Issue by ChristophAnastasiades** [biigpongsatorn/vue-element-loading#24]
Thank you for this great plugin. However I get an error in IE 11 even in the latest version (1.1.2). The problem is in the `vue-element-loading.min.js` file since there is an arrow function used which is not supported by IE 11.

**Comment by biigpongsatorn** [comment]
@ChristophAnastasiades What is your `vue-element-loading` version?

**Comment by biigpongsatorn** [comment]
@ChristophAnastasiades  Please try `1.1.3`

**Comment by ChristophAnastasiades** [comment]
@biigpongsatorn Thank you, but I still have an arrow function in the bundled file. It seems as if the code is part of the CSS sourcemaps creation. This is the part of the code I am talking about: `return(t,e)=>(function(t,e){const i=N?e.media||"default":t,a=L[i]||(L[i]={ids:new Set,styles:[]});`

**Comment by biigpongsatorn** [comment]
@ChristophAnastasiades  I just fix this bug in `vue-element-loading.min.js` manually and publish to version `1.1.5`.

Please try again.
