### ISSUE TITLE
[Feature request] Loader delay

### ISSUE THREAD

**Issue by secit-pl** [biigpongsatorn/vue-element-loading#31]
Sometime the same loading action can take from 0.01 second to 2 seconds. If the loading takes less than ~0.5 second user will only see a "blink". Is it possible to add delay which prevents from showing the loader if the "active" value will be set to true for less than X milliseconds?

**Comment by runyasak** [comment]
Hi, @biigpongsatorn  
I have make a PR to resolve this feature. 😁

Please, review on this PR #32

**Comment by secit-pl** [comment]
Thank you! :)

**Comment by secit-pl** [comment]
Could you please make a new release with this change?

**Comment by biigpongsatorn** [comment]
@secit-pl I just published version `1.1.6` for this feature.
Thanks @runyasak for the fast response. 😎

**Comment by secit-pl** [comment]
Sorry but you made the change in opposition to the feature request :(

The request was:
Show loader after X seconds if the `active` value wont change before that time to false to prevent blinking for quick loadings.

The current implementation is:
Show loader always at last for X seconds. In this case all loadings stays are shown for at last X seconds.
