### ISSUE TITLE
compatibility with Vue 3?

### ISSUE THREAD

**Issue by maharzan** [biigpongsatorn/vue-element-loading#34]
I was testing this with Vue 3 and adding 

`import VueElementLoading from 'vue-element-loading'`

and 

`<vue-element-loading :active="isActive" spinner="bar-fade-scale" color="#FF6700"/>`

in my component is giving all sorts of errors.

    Property "isActive" was accessed during render but is not defined on instance. 
    TypeError: selfHook.call is not a function
    Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

and so on..

Any fixes as Vue 3 is coming out soon..

**Comment by dacoto97** [comment]
Hi @biigpongsatorn,
The new version of vue 3 has already been released, are there plans to make this plugin compatible?

**Comment by borasusmaz** [comment]
Same here, vue3 support would be appreciated.

**Comment by runyasak** [comment]
Hi, @maharzan 
Thank you for your issue, We're working on it. 😁

**Comment by Sitronik** [comment]
Hello guys, I added pull request with vue 3 support https://github.com/biigpongsatorn/vue-element-loading/pull/38

**Comment by dacoto97** [comment]
@Sitronik I have left some comments!

**Comment by Sitronik** [comment]
> @Sitronik I have left some comments!

Ok Thanks. I changed everything as you wrote

**Comment by runyasak** [comment]
Hi, @Sitronik 
Thank you, for your contributing. That would be priceless PR for us. 😁

So, I will review now and it would be some comments.

Thank you again 😂 🙏

**Comment by Sitronik** [comment]
> Hi, @Sitronik
> Thank you, for your contributing. That would be priceless PR for us. 😁
> 
> So, I will review now and it would be some comments.
> 
> Thank you again 😂 🙏


Hi @runyasak 
Ok, you are always welcome 😁

**Comment by Sitronik** [comment]
Hi everyone who has access to npm publishing?  As I understand it, the repository owner is very busy. If you have access please make a publication with the tag **next** version 2.0.0 thanks in advance.  Anyone who already needs to use a module with vue 3 support in their projects can use **npm i vue3-element-loading**

**Comment by dacoto97** [comment]
I see that the demo is broken: https://vue-element-loading.netlify.app/

**Comment by Sitronik** [comment]
> I see that the demo is broken: https://vue-element-loading.netlify.app/

I also saw that there is such a problem, can you make a demo of the module on codeopen and post a link to the demo in the readme?

**Comment by biigpongsatorn** [comment]
Thank you all. @Sitronik  @dacoto97 @runyasak  @maharzan 

It is already fixed you can install it as `npm i vue-element-loading@next` for Vue3 compatibility and the demo page is already working.
