### ISSUE TITLE
How to start / stop loading element programmatically?

### ISSUE THREAD

**Issue by PhouvanhKCSV** [biigpongsatorn/vue-element-loading#4]
On the doc, i have to use something like this
```
<vue-element-loading :active="show" spinner="bar-fade-scale" color="#FF6700"/>
```

but how can i start/stop loading element like this for full screen
```
this.$loading.start() 
this.$loading.stop()
```

$loading could be something else to prevent conflict with other library

Thanks

**Comment by biigpongsatorn** [comment]
@PhouvanhKCSV  You have to set `this. show` = `true` or `false`.

Example
```html
<vue-element-loading :active="show" spinner="bar-fade-scale" color="#FF6700"/>
```

```js
async getSomeData () {
   this.show = true
   await fetchApi()
   this.show = false
}
```

**Comment by biigpongsatorn** [comment]
@PhouvanhKCSV  You can use it in App.vue and control via Vuex.
