### ISSUE TITLE
Bootstrap modal z-index

### ISSUE THREAD

**Issue by n-osennij** [biigpongsatorn/vue-element-loading#6]
Hi. In full-screen mode spinner have z-index=999. But [bootstrap 4](https://getbootstrap.com/) modal have z-index=1050; So full-screen spinner is under bootstrap modal.

**Comment by biigpongsatorn** [comment]
@n-osennij Can you make a pr to solve this issue?

**Comment by juliomotol** [comment]
Houston, we have a problem. I also have loader in a component behind the modal.

Since the`z-index` was set to 3000, the loader behind the modal now shows on top of the modal.  
![image](https://user-images.githubusercontent.com/21353103/119812049-4efa1800-bf1a-11eb-8545-fea10161f3bc.png)
